name: insightCloudSec Scan
author: Rapid7
description: >
  Scans a cloudformation template and saves results to disk.
inputs:
  base_url:
    description: URL of ICS server
    required: true
  api_key:
    description: Api key for server at base_url
    required: true
  config_name:
    description: Name of insightCloudSec configuration to run scan with
    required: true
  target:
    description: File(s) to scan
    required: false
    default: "./[^.git]*"
outputs:
  stdout:
    description: Output of the mimics scan command
runs:
  using: docker
  image: docker://public.ecr.aws/rapid7-insightcloudsec/ics/mimics:v1
  env:
    MIMICS_BASE_URL: ${{ inputs.base_url }}
    MIMICS_API_KEY: ${{ inputs.api_key }}
  args:
    - scan
    - ${{ inputs.target }}
    - -c
    - ${{ inputs.config_name }}
    - --report-formats
    - all
