name: insightCloudSec Scan
author: Rapid7
description: >
  Scans a cloudformation template and saves results to disk.
inputs:
  api_key:
    description: Api key for server at base_url
    required: true
  base_url:
    description: URL of ICS server
    required: true
  config_name:
    description: Name of insightCloudSec configuration to run scan with
    required: true
  log_level:
    description: Sets log level ["trace", "debug", "info", "warn", "error", "fatal"] (default "info")
    required: false
    default: "info"
  log_path:
    description: Path to write log file
    required: false
    default: "./log/mimics.log"
  report_formats:
    description: Formats of scan result report artifacts (all,sarif,html,junitxml) (default "all")
    required: false
    default: "all"
  report_path:
    description: Path to write report files
    required: false
    default: "./"
  target:
    description: File(s) to scan
    required: false
    default: "./[^.git]*"
outputs:
  stdout:
    description: Output of the mimics scan command
runs:
  using: docker
  image: docker://public.ecr.aws/rapid7-insightcloudsec/ics/mimics:v1
  env:
    MIMICS_BASE_URL: ${{ inputs.base_url }}
    MIMICS_API_KEY: ${{ inputs.api_key }}
  args:
    - scan
    - ${{ inputs.target }}
    - -c
    - ${{ inputs.config_name }}
    - --log-level
    - ${{ inputs.log_level }}
    - --log-path
    - ${{ inputs.log_path }}
    - --report-path
    - ${{ inputs.report_path }}
    - --report-formats
    - ${{ inputs.report_formats }}
