---
info:
  title: Insightcloudsec Actions
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/insightcloudsec-actions
  x-cortex-tag: insightcloudsec-actions
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: ics-miscellany
  x-cortex-groups:
  - exposure:external-ship
  x-cortex-owners:
  - name: rapid7-csp-shiftleft-devs
    type: GROUP
    provider: CORTEX
  - name: rapid7/csp-shiftleft-devs
    type: GROUP
    provider: GITHUB
openapi: 3.0.1
servers:
- url: "/"
